// AUTH ACTION TYPES
export const SIGN_UP = "SIGN_UP";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_ERROR = "SIGN_UP_ERROR";

export const SIGN_IN = "SIGN_IN";
export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS";
export const SIGN_IN_ERROR = "SIGN_IN_ERROR";

export const SAVE_USER = "SAVE_USER";
export const SAVE_USER_SUCCESS = "SAVE_USER_SUCCESS";
export const SAVE_USER_ERROR = "SAVE_USER_ERROR";

export const LOAD_USER = "LOAD_USER";
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
export const LOAD_USER_ERROR = "LOAD_USER_ERROR";

export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";

export const LOGOUT = "LOGOUT";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_ERROR = "LOGOUT_ERROR";

//RECIPE ACTION Types
export const GET_RANDOM_RECIPES = "GET_RANDOM_RECIPES";
export const GET_RANDOM_RECIPES_SUCCESS = "GET_RANDOM_RECIPES_SUCCESS";
export const GET_RANDOM_RECIPES_ERROR = "GET_RANDOM_RECIPES_ERROR";

export const GET_TRENDING_RECIPES = "GET_TRENDING_RECIPES";
export const GET_TRENDING_RECIPES_SUCCESS = "GET_TRENDING_RECIPES_SUCCESS";
export const GET_TRENDING_RECIPES_ERROR = "GET_TRENDING_RECIPES_ERROR";

export const SEARCH_RECIPES = "SEARCH_RECIPES";
export const SEARCH_RECIPES_SUCCESS = "SEARCH_RECIPES_SUCCESS";
export const SEARCH_RECIPES_ERROR = "SEARCH_RECIPES_ERROR";

export const GET_SELECTED_RECIPE = "GET_SELECTED_RECIPE";
export const GET_SELECTED_RECIPE_SUCCESS = "GET_SELECTED_RECIPE_SUCCESS";
export const GET_SELECTED_RECIPE_ERROR = "GET_SELECTED_RECIPE_ERROR";

//Bookmark/UnBookmark
export const BOOKMARK = "BOOKMARK";
export const BOOKMARK_SUCCESS = "BOOKMARK_SUCCESS";
export const BOOKMARK_ERROR = "BOOKMARK_ERROR";

export const REMOVE_BOOKMARK = "REMOVE_BOOKMARK";
export const REMOVE_BOOKMARK_SUCCESS = "REMOVE_BOOKMARK_SUCCESS";
export const REMOVE_BOOKMARK_ERROR = "REMOVE_BOOKMARK_ERROR";

//Upload Profile Image
export const UPLOAD_PROFILE_IMAGE = "UPLOAD_PROFILE_IMAGE";
export const UPLOAD_PROFILE_IMAGE_SUCCESS = "UPLOAD_PROFILE_IMAGE_SUCCESS";
export const UPLOAD_PROFILE_IMAGE_ERROR = "UPLOAD_PROFILE_IMAGE_ERROR";
